server:
  port: 80


eureka:
  client:
    register-with-eureka: true #表示是否向注册中心注册自己默认为true
    fetch-registry: true  #是否EurekaServer从抓紧已有的注册信息，默认为true。单节点无所谓，集群必须要设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-order-service