server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimeZone=GMT
    username: root
    password: Zhy123zhy

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entities #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示是否向注册中心注册自己默认为true
    fetch-registry: true  #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须要设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      # defaultZone: http://localhost:7001/eureka 单机版　
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 20